# Use the official PHP 8.1 with Apache image
FROM php:8.1-apache

# Install required packages and PHP extensions for Moodle/IOMAD
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libicu-dev \
    libpng-dev \
    libjpeg-dev \
    libzip-dev \
    zlib1g-dev \
    && docker-php-ext-configure gd --with-jpeg \
    && docker-php-ext-install gd zip intl mysqli 
    #exif soap

# Enable Apache modules for Moodle/IOMAD
RUN a2enmod rewrite && a2enmod ssl

# Set the working directory
WORKDIR /var/www/html

# Clone the IOMAD repository from GitHub
RUN git clone https://github.com/iomad/iomad.git \
    && cd iomad \
    && git checkout IOMAD_401_STABLE \
    && mv * ../ \
    && cd ../ \
    && rm -rf iomad

# Set the permissions for the web server
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Expose port 80
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2-foreground"]
